[package]
name = "EvmStdlib"
version = "1.0.0"

[addresses]
std = "0x1"
Evm = "0x2"

#[dependencies]
#MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }
#MoveNursery = { local = "../../move-stdlib/nursery" }
