[package]
name = "demo"
version = "1.0.0"


[addresses]
demo = "c2839c9eadfcbd9e3458da1c9aaab21b90b88c662f7395c0595e4dcf43e7d1ae"
signer = "0x11"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = 'https://github.com/aptos-labs/aptos-core'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-stdlib'

#[dependencies.AptosFramework]
#git = 'https://github.com/shaokun11/move-me2'
#rev = 'c19ab08d7eea43757963ba702a94169e2400afde'
#subdir = 'aptos-move/framework/aptos-framework'
#
#[dependencies.AptosStdlib]
#git = 'https://github.com/shaokun11/move-me2'
#rev = 'c19ab08d7eea43757963ba702a94169e2400afde'
#subdir = 'aptos-move/framework/aptos-stdlib'
