[package]
name = "demo"
version = "1.0.0"


[addresses]
demo = "c8bde6e83f1f55e18c8c1801e05c4eb1b82252708d300b3cf738a039ebe77dfd"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'testnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.9"
