[package]
name = "demo"
version = "1.0.0"


[addresses]
demo = "1a49e06f2a17349bd6b0cb46b79c740c05ce6ec64f049c63e970c164d7f8ec19"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'testnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.9"
