[package]
name = "demo"
version = "1.0.0"


[addresses]
demo = "ef9a45fb49470e0038ed8c737ba5db0c11cac0d8c1e5f438a3b19418c3abc7ab"


[dependencies.AptosFramework]
git = 'https://github.com/shaokun11/move-me2'
rev = 'c19ab08d7eea43757963ba702a94169e2400afde'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = 'https://github.com/shaokun11/move-me2'
rev = 'c19ab08d7eea43757963ba702a94169e2400afde'
subdir = 'aptos-move/framework/aptos-stdlib'
