[package]
name = "evm"
version = "1.0.0"


[addresses]
evm = "0x12"
old_evm = "0x111"
signer = "0x1"

#[dependencies.AptosFramework]
#git = 'https://github.com/aptos-labs/aptos-core'
#rev = 'devnet'
#subdir = 'aptos-move/framework/aptos-framework'
#
#[dependencies.AptosStdlib]
#git = 'https://github.com/aptos-labs/aptos-core'
#rev = 'devnet'
#subdir = 'aptos-move/framework/aptos-stdlib'

[dependencies.AptosFramework]
git = 'https://github.com/shaokun11/move-me2'
rev = 'acf53c7de6982aee4747b1ff47908326da52487c'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = 'https://github.com/shaokun11/move-me2'
rev = 'acf53c7de6982aee4747b1ff47908326da52487c'
subdir = 'aptos-move/framework/aptos-stdlib'